import { PropType } from 'vue';
import { CORE_INPUT_PROPS } from '../core/Input';

export const PHONE_INPUT_PROPS = {
  ...CORE_INPUT_PROPS,
  label: {
    type: String,
  },
  description: {
    type: String,
  },
  onUpdate: Function as PropType<(event: Event) => void>,
  countryCode: {
    type: String,
  },
};

export interface DialCode {
  name: string;
  dialCode: string;
  code: string;
  format?: string;
}

interface AutoCompleteMapping {
  [key: string]: string | null;
}

// Ref: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-organization
export const AUTO_COMPLETE_MAPPING: AutoCompleteMapping = {
  'customer[email]': 'email',
  'customer[first_name]': 'given-name',
  'customer[last_name]': 'family-name',
  'customer[phone]': 'tel',
  'billing_address[first_name]': 'billing given-name',
  'billing_address[last_name]': 'billing family-name',
  'billing_address[line1]': 'billing address-line1',
  'billing_address[line2]': 'billing address-line2',
  'billing_address[line3]': 'billing address-line3',
  'billing_address[company]': 'billing organization',
  'billing_address[email]': 'billing email',
  'billing_address[city]': 'billing address-level2',
  'billing_address[state]': 'billing address-level1',
  'billing.region': 'billing address-level1',
  'billing_address[zip]': 'billing postal-code',
  'billing_address[country]': 'billing country',
  'billing_address[phone]': 'billing tel',
  'shipping_address[first_name]': 'shipping given-name',
  'shipping_address[last_name]': 'shipping family-name',
  'shipping_address[line1]': 'shipping address-line1',
  'shipping_address[line2]': 'shipping address-line2',
  'shipping_address[line3]': 'shipping address-line3',
  'shipping_address[email]': 'shipping email',
  'shipping_address[company]': 'shipping organization',
  'shipping_address[city]': 'shipping address-level2',
  'shipping_address[state]': 'shipping address-level1',
  'shipping_address[zip]': 'shipping postal-code',
  'shipping_address[country]': 'shipping country',
  'shipping_address[phone]': 'billing tel',
  'shipping.region': 'shipping address-level1',
  'card[cvv]': 'cc-csc',
  'card[expiry_month]': 'cc-exp-month',
  'card[expiry_year]': 'cc-exp-year',
  'card[first_name]': null,
  'card[last_name]': null,
  'card[number]': 'cc-number',
  'card[billing_addr1]': 'billing address-line1',
  'card[billing_addr2]': 'billing address-line2',
  'card[billing_city]': 'shipping address-level2',
  'card[billing_country]': 'billing country',
  'card[billing_state]': 'billing address-level1',
  'card[billing_state_code]': null,
  'card[billing_zip]': 'billing postal-code',
};

export const DIAL_CODES: DialCode[] = [
  {
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
    format: '+.. .. ... ....',
  },
  {
    name: 'Aland Islands',
    dialCode: '+358',
    code: 'AX',
    format: '+... .. ... .. ..',
  },
  {
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
    format: '+... .. ... ....',
  },
  {
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
    format: '+... ... .. .. ..',
  },
  {
    name: 'AmericanSamoa',
    dialCode: '+1684',
    code: 'AS',
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
    format: '+... ... ...',
  },
  {
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
    format: '+... ... ... ...',
  },
  {
    name: 'Anguilla',
    dialCode: '+1264',
    code: 'AI',
  },
  {
    name: 'Antarctica',
    dialCode: '+672',
    code: 'AQ',
    format: '+... .. ....',
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    code: 'AG',
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
    format: '+.. .. ..-....-....',
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
    format: '+... .. ......',
  },
  {
    name: 'Aruba',
    dialCode: '+297',
    code: 'AW',
    format: '+... ... ....',
  },
  {
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
    format: '+.. ... ... ...',
  },
  {
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
    format: '+.. ... .........',
  },
  {
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
    format: '+... .. ... .. ..',
  },
  {
    name: 'Bahamas',
    dialCode: '+1242',
    code: 'BS',
  },
  {
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
    format: '+... .... ....',
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
    format: '+... ....-......',
  },
  {
    name: 'Barbados',
    dialCode: '+1246',
    code: 'BB',
  },
  {
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
    format: '+... .. ...-..-..',
  },
  {
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
    format: '+.. ... .. .. ..',
  },
  {
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
    format: '+... ...-....',
  },
  {
    name: 'Benin',
    dialCode: '+229',
    code: 'BJ',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Bermuda',
    dialCode: '+1441',
    code: 'BM',
  },
  {
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dialCode: '+591',
    code: 'BO',
    format: '+... ........',
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
    format: '+... .. ...-...',
  },
  {
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
    format: '+... .. ... ...',
  },
  {
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
    format: '+.. .. .....-....',
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
    format: '+... ... ....',
  },
  {
    name: 'Brunei Darussalam',
    dialCode: '+673',
    code: 'BN',
    format: '+... ... ....',
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
    format: '+... ... ... ..',
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
    format: '+... .. ... ...',
  },
  {
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Canada',
    dialCode: '+1',
    code: 'CA',
  },
  {
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
    format: '+... ... .. ..',
  },
  {
    name: 'Cayman Islands',
    dialCode: '+ 345',
    code: 'KY',
  },
  {
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Chad',
    dialCode: '+235',
    code: 'TD',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Chile',
    dialCode: '+56',
    code: 'CL',
    format: '+.. . .... ....',
  },
  {
    name: 'China',
    dialCode: '+86',
    code: 'CN',
    format: '+.. ... .... ....',
  },
  {
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
    format: '+.. ... ... ...',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
    format: '+.. ... ... ...',
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
    format: '+.. ... .......',
  },
  {
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
    format: '+... ... .. ..',
  },
  {
    name: 'Congo',
    dialCode: '+242',
    code: 'CG',
    format: '+... .. ... ....',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dialCode: '+243',
    code: 'CD',
    format: '+... ... ... ...',
  },
  {
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
    format: '+... .. ...',
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
    format: '+... .... ....',
  },
  {
    name: "Cote d'Ivoire",
    dialCode: '+225',
    code: 'CI',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
    format: '+... .. ... ....',
  },
  {
    name: 'Cuba',
    dialCode: '+53',
    code: 'CU',
    format: '+.. . .......',
  },
  {
    name: 'Cyprus',
    dialCode: '+357',
    code: 'CY',
    format: '+... .. ......',
  },
  {
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
    format: '+... ... ... ...',
  },
  {
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
    format: '+.. .. .. .. ..',
  },
  {
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Dominica',
    dialCode: '+1767',
    code: 'DM',
  },
  {
    name: 'Dominican Republic',
    dialCode: '+1849',
    code: 'DO',
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
    format: '+... .. ... ....',
  },
  {
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
    format: '+.. ... ... ....',
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
    format: '+... .... ....',
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
    format: '+... ... ... ...',
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
    format: '+... . ... ...',
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
    format: '+... .... ....',
  },
  {
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
    format: '+... .. ... ....',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    code: 'FK',
  },
  {
    name: 'Faroe Islands',
    dialCode: '+298',
    code: 'FO',
    format: '+... ......',
  },
  {
    name: 'Fiji',
    dialCode: '+679',
    code: 'FJ',
    format: '+... ... ....',
  },
  {
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
    format: '+... .. ... .. ..',
  },
  {
    name: 'France',
    dialCode: '+33',
    code: 'FR',
    format: '+.. . .. .. .. ..',
  },
  {
    name: 'French Guiana',
    dialCode: '+594',
    code: 'GF',
    format: '+... ... .. .. ..',
  },
  {
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
    format: '+... .. .. ..',
  },
  {
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
    format: '+... ... ....',
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
    format: '+... ... .. .. ..',
  },
  {
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
    format: '+.. ... .........',
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
    format: '+... .. ... ....',
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
    format: '+... ... .....',
  },
  {
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
    format: '+.. ... ... ....',
  },
  {
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
    format: '+... .. .. ..',
  },
  {
    name: 'Grenada',
    dialCode: '+1473',
    code: 'GD',
  },
  {
    name: 'Guadeloupe',
    dialCode: '+590',
    code: 'GP',
  },
  {
    name: 'Guam',
    dialCode: '+1671',
    code: 'GU',
  },
  {
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
    format: '+... .... ....',
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
    format: '+.. .... ......',
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
    format: '+... ... .. .. ..',
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
    format: '+... ... ....',
  },
  {
    name: 'Guyana',
    dialCode: '+595',
    code: 'GY',
    format: '+... .. .......',
  },
  {
    name: 'Haiti',
    dialCode: '+509',
    code: 'HT',
    format: '+... .. .. ....',
  },
  {
    name: 'Holy See (Vatican City State)',
    dialCode: '+379',
    code: 'VA',
  },
  {
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
    format: '+... ....-....',
  },
  {
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
    format: '+... .... ....',
  },
  {
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
    format: '+.. .. ... ....',
  },
  {
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
    format: '+... ... ....',
  },
  {
    name: 'India',
    dialCode: '+91',
    code: 'IN',
    format: '+.. .. .. ......',
  },
  {
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
    format: '+.. ...-...-...',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dialCode: '+98',
    code: 'IR',
    format: '+.. ... ... ....',
  },
  {
    name: 'Iraq',
    dialCode: '+964',
    code: 'IQ',
    format: '+... ... ... ....',
  },
  {
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
    format: '+... .. ... ....',
  },
  {
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
    format: '+.. .... ......',
  },
  {
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
    format: '+... ..-...-....',
  },
  {
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
    format: '+.. .. .... ....',
  },
  {
    name: 'Jamaica',
    dialCode: '+1876',
    code: 'JM',
  },
  {
    name: 'Japan',
    dialCode: '+81',
    code: 'JP',
    format: '+.. ..-....-....',
  },
  {
    name: 'Jersey',
    dialCode: '+44',
    code: 'JE',
    format: '+.. .... ......',
  },
  {
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
    format: '+... . .... ....',
  },
  {
    name: 'Kazakhstan',
    dialCode: '+77',
    code: 'KZ',
  },
  {
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
    format: '+... .. .......',
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: '+850',
    code: 'KP',
    format: '+... ... ... ....',
  },
  {
    name: 'Korea, Republic of South Korea',
    dialCode: '+82',
    code: 'KR',
    format: '+.. ..-....-....',
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
    format: '+... ... .....',
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
    format: '+... ... ... ...',
  },
  {
    name: 'Laos',
    dialCode: '+856',
    code: 'LA',
    format: '+... .. .. ... ...',
  },
  {
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
    format: '+... .. ... ...',
  },
  {
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
    format: '+... .. ... ...',
  },
  {
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
    format: '+... .... ....',
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
    format: '+... ... ... ...',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dialCode: '+218',
    code: 'LY',
    format: '+... ..-.......',
  },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
    format: '+... ... ... ...',
  },
  {
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
    format: '+... ... .....',
  },
  {
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
    format: '+... .. .. .. ...',
  },
  {
    name: 'Macao',
    dialCode: '+853',
    code: 'MO',
    format: '+... .... ....',
  },
  {
    name: 'Macedonia',
    dialCode: '+389',
    code: 'MK',
    format: '+... .. ... ...',
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
    format: '+... .. .. ... ..',
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
    format: '+... ... .. .. ..',
  },
  {
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
    format: '+.. ...-.... ....',
  },
  {
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
    format: '+... ...-....',
  },
  {
    name: 'Mali',
    dialCode: '+223',
    code: 'ML',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Malta',
    dialCode: '+356',
    code: 'MT',
    format: '+... .... ....',
  },
  {
    name: 'Marshall Islands',
    dialCode: '+692',
    code: 'MH',
    format: '+... ...-....',
  },
  {
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
    format: '+... ... .. .. ..',
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
    format: '+... .... ....',
  },
  {
    name: 'Mayotte',
    dialCode: '+262',
    code: 'YT',
  },
  {
    name: 'Mexico',
    dialCode: '+52',
    code: 'MX',
    format: '+.. ... ... ... ....',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dialCode: '+691',
    code: 'FM',
    format: '+... ... ....',
  },
  {
    name: 'Moldova',
    dialCode: '+373',
    code: 'MD',
    format: '+... ... .. ...',
  },
  {
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
    format: '+... . .. .. .. ..',
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
    format: '+... .... ....',
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
    format: '+... .. ... ...',
  },
  {
    name: 'Montserrat',
    dialCode: '+1664',
    code: 'MS',
  },
  {
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
    format: '+... ...-......',
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
    format: '+... .. ... ....',
  },
  {
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
    format: '+.. . ... ....',
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
    format: '+... .. ... ....',
  },
  {
    name: 'Nauru',
    dialCode: '+674',
    code: 'NR',
    format: '+... ... ....',
  },
  {
    name: 'Nepal',
    dialCode: '+977',
    code: 'NP',
    format: '+... ...-.......',
  },
  {
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
    format: '+.. . ........',
  },
  {
    name: 'Netherlands Antilles',
    dialCode: '+599',
    code: 'AN',
    format: '+... . ... ....',
  },
  {
    name: 'New Caledonia',
    dialCode: '+687',
    code: 'NC',
    format: '+... ........',
  },
  {
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
    format: '+.. .. ... ....',
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
    format: '+... .... ....',
  },
  {
    name: 'Niger',
    dialCode: '+227',
    code: 'NE',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
    format: '+... ... ... ....',
  },
  {
    name: 'Niue',
    dialCode: '+683',
    code: 'NU',
  },
  {
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
    format: '+... .. ....',
  },
  {
    name: 'Northern Mariana Islands',
    dialCode: '+1670',
    code: 'MP',
  },
  {
    name: 'Norway',
    dialCode: '+47',
    code: 'NO',
    format: '+.. ... .. ...',
  },
  {
    name: 'Oman',
    dialCode: '+968',
    code: 'OM',
    format: '+... .... ....',
  },
  {
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
    format: '+.. ... .......',
  },
  {
    name: 'Palau',
    dialCode: '+680',
    code: 'PW',
    format: '+... ... ....',
  },
  {
    name: 'Palestinian Territory, Occupied',
    dialCode: '+970',
    code: 'PS',
    format: '+... ... ... ...',
  },
  {
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
    format: '+... ....-....',
  },
  {
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
    format: '+... ... ....',
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
    format: '+... .. .......',
  },
  {
    name: 'Peru',
    dialCode: '+51',
    code: 'PE',
    format: '+.. ... ... ...',
  },
  {
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
    format: '+.. .... ......',
  },
  {
    name: 'Pitcairn',
    dialCode: '+872',
    code: 'PN',
  },
  {
    name: 'Poland',
    dialCode: '+48',
    code: 'PL',
    format: '+.. .. ... .. ..',
  },
  {
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
    format: '+... ... ... ...',
  },
  {
    name: 'Puerto Rico',
    dialCode: '+1939',
    code: 'PR',
  },
  {
    name: 'Qatar',
    dialCode: '+974',
    code: 'QA',
    format: '+... .... ....',
  },
  {
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
    format: '+.. .. ... ....',
  },
  {
    name: 'Russia',
    dialCode: '+7',
    code: 'RU',
    format: '+. ... ...-..-..',
  },
  {
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
    format: '+... ... ... ...',
  },
  {
    name: 'Reunion',
    dialCode: '+262',
    code: 'RE',
  },
  {
    name: 'Saint Barthelemy',
    dialCode: '+590',
    code: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '+290',
    code: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '+1869',
    code: 'KN',
  },
  {
    name: 'Saint Lucia',
    dialCode: '+1758',
    code: 'LC',
  },
  {
    name: 'Saint Martin',
    dialCode: '+590',
    code: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    code: 'PM',
    format: '+... .. .. ..',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1784',
    code: 'VC',
  },
  {
    name: 'Samoa',
    dialCode: '+685',
    code: 'WS',
  },
  {
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Sao Tome and Principe',
    dialCode: '+239',
    code: 'ST',
    format: '+... ... ....',
  },
  {
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
    format: '+... .. ... ....',
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
    format: '+... .. ... .. ..',
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
    format: '+... .. .......',
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
    format: '+... . ... ...',
  },
  {
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
    format: '+... .. ......',
  },
  {
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
    format: '+.. .... ....',
  },
  {
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
    format: '+... ... ... ...',
  },
  {
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
    format: '+... .. ... ...',
  },
  {
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
    format: '+... ... ....',
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
    format: '+... .. .......',
  },
  {
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
    format: '+.. .. ... ....',
  },
  {
    name: 'South Sudan',
    dialCode: '+211',
    code: 'SS',
    format: '+... ... ... ...',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '+500',
    code: 'GS',
  },
  {
    name: 'Spain',
    dialCode: '+34',
    code: 'ES',
    format: '+.. ... .. .. ..',
  },
  {
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
    format: '+.. .. . ......',
  },
  {
    name: 'Sudan',
    dialCode: '+249',
    code: 'SD',
    format: '+... .. ... ....',
  },
  {
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
    format: '+... ...-....',
  },
  {
    name: 'Svalbard and Jan Mayen',
    dialCode: '+47',
    code: 'SJ',
    format: '+.. ... .. ...',
  },
  {
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
    format: '+... .... ....',
  },
  {
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
    format: '+.. ..-... .. ..',
  },
  {
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
    format: '+.. .. ... .. ..',
  },
  {
    name: 'Syrian Arab Republic',
    dialCode: '+963',
    code: 'SY',
    format: '+... ... ... ...',
  },
  {
    name: 'Taiwan',
    dialCode: '+886',
    code: 'TW',
    format: '+... ... ... ...',
  },
  {
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
    format: '+... ... .. ....',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dialCode: '+255',
    code: 'TZ',
    format: '+... ... ... ...',
  },
  {
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
    format: '+.. .. ... ....',
  },
  {
    name: 'Timor-Leste',
    dialCode: '+670',
    code: 'TL',
    format: '+... .... ....',
  },
  {
    name: 'Togo',
    dialCode: '+228',
    code: 'TG',
    format: '+... .. .. .. ..',
  },
  {
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
    format: '+... ... ....',
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '+1868',
    code: 'TT',
  },
  {
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
    format: '+... .. ... ...',
  },
  {
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
    format: '+.. ... ... ....',
  },
  {
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
    format: '+... .. ..-..-..',
  },
  {
    name: 'Turks and Caicos Islands',
    dialCode: '+1649',
    code: 'TC',
  },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
    format: '+... ... ......',
  },
  {
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
    format: '+... .. ... ....',
  },
  {
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
    format: '+... .. ... ....',
  },
  {
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
    format: '+.. .... ......',
  },
  {
    name: 'United States',
    dialCode: '+1',
    code: 'US',
  },
  {
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
    format: '+... .... ....',
  },
  {
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
    format: '+... .. ... .. ..',
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
    format: '+... ... ....',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dialCode: '+58',
    code: 'VE',
    format: '+.. ...-.......',
  },
  {
    name: 'Vietnam',
    dialCode: '+84',
    code: 'VN',
    format: '+.. .. ... .. ..',
  },
  {
    name: 'Virgin Islands, British',
    dialCode: '+1284',
    code: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    dialCode: '+1340',
    code: 'VI',
  },
  {
    name: 'Wallis and Futuna',
    dialCode: '+681',
    code: 'WF',
    format: '+... .. .. ..',
  },
  {
    name: 'Yemen',
    dialCode: '+967',
    code: 'YE',
    format: '+... ... ... ...',
  },
  {
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
    format: '+... .. .......',
  },
  {
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
    format: '+... .. ... ....',
  },
];
